[build]
builder = "nixpacks"



[[services]]
name = "backend"
root = "backend"
buildPath = "backend"
startCommand = "/bin/bash -c \"conda run --no-capture-output -n brep_mfr uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}\""

[services.build]
builder = "docker"
dockerfilePath = "Dockerfile"

[[services]]
name = "frontend"
root = "frontend"
buildPath = "frontend"
buildCommand = "npm run build"
startCommand = "npm run preview -- --host --port ${PORT:-4173}"

[services.build]
builder = "nixpacks"
