name: brep_mfr
channels:
  - pytorch
  - dglteam/label/cu117
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - dgl=1.0.0
  - pythonocc-core=7.7.0
  - pip
  - pip:
    - fastapi
    - uvicorn
    - python-multipart
    - supabase
    - numpy==1.23.5
    - pytorch-lightning==1.8.6
    - omegaconf==2.1.1
    - hydra-core==1.1.2
    - torchmetrics==0.9.3
    - torch-geometric==2.3.1
    - fairseq==0.12.2
